apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress-ssl
spec:
  rules:
  - host: wps.tsatalis.cloudns.cl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-clip
            port: 
              number: 5000
  tls:
    - hosts: 
      - wps.tsatalis.cloudns.cl
      secretName: tls-secret